export const ActionTypes = {
    SET_WEATHERS: "SET_WEATHERS",
    SELECTED_WEATHER: "SELECTED_WEATHER",
    REMOVE_SELECTED_WEATHER: "REMOVE_WEATHER",
    SET_USER: "SET_USER",
    FIND_USER: "FIND_USER"
};